accelerate launch --config_file configs/accelerator_singlegpu_config.yaml examples/finetuner.py \
        --output_dir '/home/deepanshu/LMFlow-diffusion-main/examples/model' \
        --enable_xformers_memory_efficient_attention True \
        --gradient_accumulation_steps 1 \
        --lr_scheduler 'constant' \
        --learning_rate 8e-6 \
        --lr_warmup_steps 0 \
        --max_train_steps 800 \
        --gradient_checkpointing True \
        --max_grad_norm 1 \
        --tracker_project_name "text2image-fine-tune" \
        --pretrained_model_name_or_path "runwayml/stable-diffusion-v1-5" \
        --use_ema False \
        --use_lora True \
        --resolution 512 \
        --dataset_name 'lambdalabs/pokemon-blip-captions' \
        --train_batch_size 40 \
        --noise_offset 0 \
        --overrode_init_dataset False \
        --validation_prompts 'a yellow pokemon with red cheeks' \
        --report_to 'wandb' \
        --validation_epochs 21 \
