accelerate launch --config_file configs/accelerator_singlegpu_config.yaml examples/raft.py \
        --output_dir '/home/deepanshu/LMFlow-diffusion-main/examples/model' \
        --enable_xformers_memory_efficient_attention True \
        --gradient_accumulation_steps 1 \
        --lr_scheduler 'constant' \
        --learning_rate 9e-6 \
        --lr_warmup_steps 0 \
        --max_train_steps 50 \
        --gradient_checkpointing True \
        --max_grad_norm 1 \
        --tracker_project_name "text2image-fine-tune" \
        --pretrained_model_name_or_path "runwayml/stable-diffusion-v1-5" \
        --use_ema False \
        --use_lora True \
        --resolution 256 \
        --dataset_name '/home/deepanshu/LMFlow-diffusion-main/a' \
        --train_batch_size 5 \
        --topk 5 \
        --inference_batch_size 20 \
        --epochs 8 \
        --num_images_per_prompt 10 \
        --clip_model_pretrained_or_path 'ViT-L-14' \
        --score_model 'aesthetic' \
        --save_finetune_images True \
        --grid True \
        --num_inference_steps  50\
        --pipeline_scheduler 'DDPMScheduler' \
        --negative_prompt 'painting, sketching, sketches, drawing, ugly , deformed , bad , dark' \
        --save_raft_images True 

